version: '3'

services:
  next:
    build: ./next
    restart: always
    volumes:
      - /app/node_modules
      - ./next:/app
  api:
    build: ./api
    restart: always
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      SECRET_KEY: random_secret_key_65478989_4324324
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9000:9000'
    depends_on:
      - api
      - adminer

volumes:
  postgres_data:
