import HomeNotesView from '@/sections/home/view/home-notes-view';
import HomeTodoView from '@/sections/home/view/home-todo-view';
import { Typography } from '@mui/material';

import { Metadata } from 'next/types';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function Home() {
  return (
    <main>
      <Typography
        variant='h3'
        sx={{ textAlign: 'center', textTransform: 'capitalize' }}
      >
        Workspace
      </Typography>
      <HomeTodoView />
      <HomeNotesView />
    </main>
  );
}
